#
# Used for local development
#

version: '3'
networks:
  tactile:
    driver: bridge

services:
  redis-local:
    image: "redis:6.2.6"
    container_name: redis-local
    ports:
      - "6379:6379"
    restart: on-failure
